### ISSUE TITLE
Android 4.2 marker + popup

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/MobileMapStarter2#15]
Reported by Andrew G:

* Samsung Galaxy S4 phone
* Android 4.2.2 

clicking on a marker and popup - it causes the tile layers to distort so that the boundaries no longer line up properly

**Comment by TinArgus** [comment]
To give a little more information on this issue, it only appears after zooming in and out a little bit and clicking / tapping around. At some point it seems that the zoom level and the tile zoom level get out of sync so that adjacent tiles load different zoom levels. Once the map is glitched the only way to get a normal map again is to restart the app. I no longer suspect that it is related to popups, but perhaps the zoom controls (double-click and pinch)?

This issue applies both to tile layers served by OSM and other providers as well as a static image that is loaded using the plugin L.ImageOverlay.Rotated referenced in [Issue 16](https://github.com/GreenInfo-Network/MobileMapStarter2/issues/16)

See the following screenshot for an example of the tile misalignment when viewing OSM data tiles.

![image](https://user-images.githubusercontent.com/19586500/30233832-c38af29c-94bd-11e7-867e-61da6c190f7d.png)

**Comment by TinArgus** [comment]
The plot thickens...I decided to do a little testing on your unaltered version of Mobile Map Starter and I was unable to recreate the tile misalignment issue on my Galaxy S4. This leads me to believe that the problem must be in one of the additional plugins that I am loading, and thus it is not an issue with this repository. In the future if I have some spare time I might try isolating the culprit, but since 90% of Android devices are version 5 or more recent, I'm not too concerned.

**Comment by gregallensworth** [comment]
Well that's interesting, that some other Leaflet addon could have contributed to this. Doesn't SOUND likely, but if it cannot be replicated then...

I do want to check into this, though. It could be worth an hour, to head off issues others may encounter, or to at least document a known issue:
* Can I get a list of the Leaflet addons you're using in the app which does misbehave, and maybe some sample code as to how they're being added to the `L.map`?
* And to confirm: the issue would happen any time you open a popup bound to a marker?

I'll have my office put back together and be able to get back to work on this, in a couple more days.

**Comment by gregallensworth** [comment]
So far I have been unable to replicate this problem, using Android 4.2 on an emulator. I have tried using MobileMapStarter2 and also with the app which you sent via private message. As such, I don't have much in the way of new theories or help to offer here...

**Comment by TinArgus** [comment]
This problem will not effect most users, so I'm not too concerned. Thanks for trying to troubleshoot!
