### ISSUE TITLE
Bundling tiles with my app? / Allow non-offline basemaps

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/MobileMapStarter2#19]
@tinargus Asks: As a possible alternative to using tile servers, how would I go about including a set of downloaded tiles with the release to make it offline from the start and avoid the need for a server connection?

**Comment by gregallensworth** [comment]
Basically, this would be done as follows:
* Download the tile set through some other means. Maybe fire up MobileMapStarter, then copy the tiles folders off of your device. Or perhaps use https://www.npmjs.com/package/xyz-affair to generate a list of all XYZ coordinates and generate a list of all possible tile URLs.
* Add the tile set (or tile sets plural) into your `www/` folder, so they're part of the app. I would dedicate a subfolder to it, e.g. `www/tilesets/`
* Set the L.TileLayer `url` to that relative URL: `/tilesets/mytopo/{z}/{x}/{y}.png`

The catch here, is that now you'll need to do some rewriting The provided implementation presumes that all maps listed under `basemaps` would be created as L.TileLayer.Cordova and would be cached. For an on-device this of course doesn't make sense.

If you wanted to use **only** on-device maps, it should be fairly easy to strip out the caching UI, L.TileLayer.Cordova, and the offlineCacheXXX family of functions. If you wanted to use both, it could get more tedious to handle both. But I have an idea for an improvement here...

**Comment by gregallensworth** [comment]
Proposed improvement:
* Add to the `base maps` setting in `settings.js` a `enableOffline` flag, and document it.
* In initMapAndGeolocation() where we iterate over the base maps and create L.TileLayer.Cordova instances, check the `enableOffline` flag and if it's not set then create a L.TileLayer instead.
* In the offlineCacheXXX() family of functions where we loop over layers to populate them, clear them, etc., add checks that they are L.TileLayer.Cordova

This would allow one to use both offline-capable tile layers, and also "plain" tile layers without offline caching. The intended use cases would be:
* one simply doesn't want to allow offline caching for the layer, e.g. terms of use, server load, or just not useful
* a tile layer whose tiles are hosted on-device in a folder under `www/` which are therefore always available offline anyway

**Comment by gregallensworth** [comment]
There we go. As of e0d5d1f the settings.js supports a `offlineCache` setting, which causes some layers to not be L.TileLayer.Cordova at all. The various cache-management functions have also been adjusted to act only upon those which are L.TileLayer.Cordova

**Comment by TinArgus** [comment]
This is great! Thanks for adopting my suggested improvement so quickly! I think this is a really helpful option, especially for maps that cover a limited area.

One note, it seems that you must have a rooted android device and a root-enabled file explorer in order to access the tiles where they are stored in the /data/data/XXX folder if you want to get the tiles using MMS.

**Comment by gregallensworth** [comment]
If you plug in your phone, your PC should be able to access all files on the phone's internal store and the SD card, no?

Once you get the tiles off the phone and into your application bundle (the `www/` folder) the tiles will be part of the app.

**Comment by TinArgus** [comment]
I am not sure if this is the case or not. I had issues getting the driver installed on my old phone and for this reason I do most of my testing on an emulated device. I tried plugging in a couple of newer devices without root and did not appear to have access to the data folders.

This is a really nice feature and I plan to use it in most of my apps. Retaining the option to also load from a L.TileLayer.Cordova layer makes this truly versatile!

**Comment by TinArgus** [comment]
An update on this. I have finally tested this out and am having some issues. I think I understand what the problem is.

I downloaded some imagery tiles using the download offline function in the app. I want to include these images bundled with the app, so I moved them from the /data/data/imagery/ folder on the phone to the www/imagery/ folder in the project.

I want to load these images as a normal tile server, but with the url pointed to the www/imagery/ folder where the tiles are contained. The problem is, the address expects these files to be in the standard folder structure /imagery/{z}/{x}/{y}.png but instead they named as L.tileLayer.Cordova offline mode files: /imagery/name-z-x-y.png

If I try to load the folder as an offline tile, it doesn't work because L.tileLayer.Cordova expects the files to be in the /data/data/imagery/ folder on the device.

It seems that I either need to arrange the files into the folder structure of www/imagery/z/x/y/ or need a way for offlineCache: false mode to interpret the /name-z-x-y.png filename like L.tileLayer.Cordova does. I suppose a third solution would be to automatically write the /www/imagery/ folder to the /data/data/imagery/ offline cache folder on the device upon initial install. 

I hope that I explained this clearly...any ideas as to a solution? Thanks for your help!
